on:
  workflow_call:
    secrets:
      github-token: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: detect_tag
        with:
          create-tag: false
          version-command: ruby -e 'puts File.read("CHANGELOG.md")[/(\d+\.\d+\.\d+)/, 1]'
      - uses: mathieudutour/github-tag-action@v5.6
        with:
          custom_tag: ${{ steps.detect_tag.outputs.current-version }}
          github_token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}
        if: ${{ steps.detect_tag.outputs.previous-version != steps.detect_tag.outputs.current-version }}
