on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: tag-new-version
        with:
          version-command: cat VERSION
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.tag-new-version.outputs.tag }}
        if: ${{ steps.tag-new-version.outputs.tag }}
      - name: Push HEAD to main version branch
        run: |
          branch_name=$(echo "${{ steps.tag-new-version.outputs.tag }}" | sed -E "s/(v[0-9]+)\..+/\1/")
          git push --force origin "HEAD:refs/heads/${branch_name}"
        if: ${{ steps.tag-new-version.outputs.tag }}
