on:
  workflow_call:
    inputs:
      build:
        description: Whether to run `cargo build`
        default: true
        type: boolean
      clippy:
        description: Whether to run `cargo clippy`
        default: true
        type: boolean
      fmt:
        description: Whether to run `cargo fmt`
        default: true
        type: boolean
      test:
        description: Whether to run `cargo test`
        default: true
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chetan/git-restore-mtime-action@v1.1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: r7kamura/rust-problem-matchers@v1
      - name: cargo fmt
        run: |-
          rustup component add rustfmt
          cargo fmt -- --check
        if: ${{ inputs.fmt }}
      - name: cargo build
        run: cargo build --all-features
        if: ${{ inputs.build }}
      - name: cargo clippy
        run: |-
          rustup component add clippy
          cargo clippy -- -D warnings
        if: ${{ inputs.clippy }}
      - name: cargo test
        run: cargo test --all-features
        if: ${{ inputs.test }}
